/// all the reduces realted to the todo application

import {createSlice, nanoid} from "@reduxjs/toolkit" ;
const initialState  = {
    todos: [
        {
            id : "1",
            task:"Demo task",
            isDone : false
         }
        ],

}
export const todoSlice = createSlice({
    name: "todo",
    initialState,
    reducers :{

        // reducer to add a new todo
        addTodo : (state, action)=>{
            const newTodo = {
                id : nanoid(), //get unique id, alternateto uuid
                task : action.payload,
                isDone : false,
            }
            state.todos.push(newTodo); // direct mutation unlike destructuring in react, here reference is passed and in rect we use to get the copy.
            // benefit is direct mutation
        
        },
        // reducer to delete the todo
        deleteTodo : (state, action)=>{
            
            const deleteTodo = action.payload;
            // remove the todo based on the id got in action
            state.todos = state.todos.filter((todo) => todo.id != deleteTodo)


        },
        // reducer to mark the state as done
        markAsDone : (state, action)=> {
            const DoneTodo = action.payload;
            state.todos.map((todo) =>{
                if(todo.id == DoneTodo){
                    todo.isDone = true;
                }
            } )
        }
         
    }
})


export default todoSlice.reducer;


// action creators are generated for each case reducer function
// automatically done by redux toolkit
// action objects are generated by the redux toolkit, we just need to provide the functions
export const {addTodo ,
                deleteTodo,
                markAsDone} = todoSlice.actions;